{
 "title": "PharmaOps - Observability Overview",
 "tags": [
  "pharmaops",
  "loki",
  "prometheus",
  "observability"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "pharmaops" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values({namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API - Requests rate (RPS)",
   "type": "timeseries",
   "description": "Requests per second (Micrometer http_server_requests_seconds_count).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "API - Error rate (5xx RPS)",
   "type": "timeseries",
   "description": "5xx error rate based on http_server_requests_seconds_count {status=~\"5..\"}",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\".+\",status=~\".+\"}[15m]))",
     "legendFormat": "5xx RPS"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API - Latency p95 (seconds)",
   "type": "timeseries",
   "description": "p95 latency based on Micrometer histogram buckets (http_server_requests_seconds_bucket).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=~\".+\",pod=~\".+\"}[15m]))/sum(rate(http_server_requests_seconds_count{namespace=~\".+\",pod=~\".+\"}[15m]))\r\n\r\n",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "PharmaOps - Application Logs",
   "type": "logs",
   "description": "All application logs for PharmaOps API",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=~\".+\", pod=~\".+\", container=~\".+\"}"
    }
   ]
  },
  {
   "title": "PharmaOps - Errors (Live)",
   "type": "logs",
   "description": "Error logs only (searches for ERROR keyword).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=~\".+\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "PharmaOps - Audit / Hibernate traces",
   "type": "logs",
   "description": "Audit/DB traces (Hibernate + audit_events).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=~\".+\", pod=~\".+\"} |= \"audit_events\" "
    },
    {
     "direction": "backward",
     "expr": " {namespace=~\".+\", pod=~\".+\"} |= \"Audit\""
    },
    {
     "direction": "backward",
     "expr": "{namespace=\".+\", pod=~\".+\"} |= \"Hibernate\""
    }
   ]
  }
 ]
}