grafana:
  enabled: true
  adminPassword: admin

  image:
    tag: "12.3.1"

  livenessProbe:
    initialDelaySeconds: 1200
    timeoutSeconds: 30
    periodSeconds: 10
    failureThreshold: 10

  readinessProbe:
    initialDelaySeconds: 300
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 30

  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      url: http://loki.loki.svc.cluster.local:3100
      access: proxy

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

nodeExporter:
  enabled: false

prometheus-node-exporter:
  enabled: false
